baseURL = 'https://riiku.fun/'
title = "(＃￣□￣)o━━☆ ⁂"
theme = "hugo-bearblog"
languageCode = "pt"
defaultContentLanguage = "pt"
enableRobotsTXT = true
timezone = "America/Fortaleza"
copyright = "Por Riiku com ♡"

[languages]
[languages.pt]
[languages.pt.params]
madeWith = "Feito usando [Hugo](https://gohugo.io/) e [Bear Cub](https://github.com/clente/hugo-bearcub)"


[params]
favicon = "/images/favicon.webp"
dateFormat = "02/01/2006"
description = "Um dia eu ainda vou aprender a escrever, até lá, vou seguir com esse blog"
[params.author]
name = "Riiku"
email = "ricardoars@tuta.io"
mastodon = "https://tech.lgbt/@riiku"
bluesky = "https://bsky.app/profile/riiku.fun"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
name = "inicio"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "blog"
url = "/tags/blog"
weight = 3

[[menu.main]]
name = "tutoriais"
url = "/tags/tutorial"
weight = 4

[[menu.main]]
name = "sobre"
url = "/about"
weight = 5
