baseURL = 'https://riiku.fun/'
defaultContentLanguage = "pt"
title = "(＃￣□￣)o━━━☆ ⁂"
theme = "hugo-bearcub"
enableRobotsTXT = true
timezone = "America/Fortaleza"
copyright = "Por Riiku"

[languages]
  [languages.pt]
    [languages.pt.params]
      madeWith = "Feito com [Bear Cub](https://github.com/clente/hugo-bearcub)"


[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false

[params]
dateFormat = "02/01/2006"
themeStyle = "original"
favicon = "images/favicons/favicon.ico"
  [params.social]
    bluesky = "riiku.fun"
    lastfm = "riicu"
    mastodon = "riiku@tech.lgbt"
    letterboxd = "echoriiku"
    github = "echoriiku"
  [params.author]
    name = "Riiku"
    email = "ricardoars@tuta.io"


[[menu.main]]
name = "inicio"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "sobre"
url = "/about"
weight = 3
